package org.acme.catalog.product.domain;

import java.time.Instant;
import java.util.UUID;

/**
 * Immutable domain model of a Discord server (guild).
 *
 * <p>
 * A guild owns its channels and roles. The identifier is generated by the
 * application, never by the database.
 */
public record Guild(UUID id, String name, Instant createdAt) {

    /**
     * Compact constructor enforcing the business invariants.
     *
     * @throws IllegalArgumentException if a component is missing or empty
     */
    public Guild {
        if (id == null) {
            throw new IllegalArgumentException("Id cannot be null");
        }
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Guild name cannot be null or empty");
        }
        if (createdAt == null) {
            throw new IllegalArgumentException("CreatedAt cannot be null");
        }
    }

    /**
     * Creates a new guild with a generated identifier and the current date.
     *
     * @param name the guild name
     * @return a valid guild
     */
    public static Guild of(String name) {
        return new Guild(UUID.randomUUID(), name, Instant.now());
    }
}
