package org.acme.catalog.product.infrastructure.persistence;

import jakarta.persistence.*;
import java.util.UUID;
import org.acme.catalog.product.domain.ChannelType;

/**
 * JPA entity mapping a channel to the {@code channels} table.
 *
 * <p>
 * Owning side of the relation with the guild: it carries the foreign key
 * {@code guild_id}. A channel name is unique within a guild, not globally,
 * hence the composite unique constraint.
 */
@Entity
@Table(name = "channels", uniqueConstraints = @UniqueConstraint(columnNames = { "guild_id", "name" }))
public class ChannelEntity {

    /** Identifier generated by the application (no {@code @GeneratedValue}). */
    @Id
    private UUID id;

    @ManyToOne(optional = false)
    @JoinColumn(name = "guild_id", nullable = false)
    private GuildEntity guild;

    @Column(nullable = false)
    private String name;

    /** Stored as text: inserting a new constant never shifts existing data. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ChannelType type;

    private String topic;

    /** Default constructor required by the JPA specification. */
    public ChannelEntity() {
    }

    /**
     * Convenience constructor used by the mapper.
     *
     * @param id    the identifier
     * @param guild the owning guild
     * @param name  the channel name
     * @param type  the channel kind
     * @param topic the optional topic
     */
    public ChannelEntity(UUID id, GuildEntity guild, String name, ChannelType type, String topic) {
        this.id = id;
        this.guild = guild;
        this.name = name;
        this.type = type;
        this.topic = topic;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public GuildEntity getGuild() {
        return guild;
    }

    public void setGuild(GuildEntity guild) {
        this.guild = guild;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ChannelType getType() {
        return type;
    }

    public void setType(ChannelType type) {
        this.type = type;
    }

    public String getTopic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }
}
