package org.acme.catalog.product.infrastructure.persistence;

import jakarta.persistence.*;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity mapping a guild to the {@code guilds} table.
 *
 * <p>
 * Inverse side of the one-to-many relations with channels and roles
 * ({@code mappedBy}). The UML composition is translated into
 * {@code cascade = ALL} and {@code orphanRemoval = true}: deleting a guild
 * deletes its channels and roles.
 */
@Entity
@Table(name = "guilds")
public class GuildEntity {

    /** Identifier generated by the application (no {@code @GeneratedValue}). */
    @Id
    private UUID id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private Instant createdAt;

    @OneToMany(mappedBy = "guild", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ChannelEntity> channels = new ArrayList<>();

    @OneToMany(mappedBy = "guild", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<RoleEntity> roles = new ArrayList<>();

    /** Default constructor required by the JPA specification. */
    public GuildEntity() {
    }

    /**
     * Convenience constructor used by the mapper.
     *
     * @param id        the identifier
     * @param name      the guild name
     * @param createdAt the creation date
     */
    public GuildEntity(UUID id, String name, Instant createdAt) {
        this.id = id;
        this.name = name;
        this.createdAt = createdAt;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public List<ChannelEntity> getChannels() {
        return channels;
    }

    public List<RoleEntity> getRoles() {
        return roles;
    }
}
