package org.acme.catalog.product.infrastructure.persistence;

import jakarta.persistence.*;
import java.util.UUID;

/**
 * JPA entity mapping a role to the {@code roles} table.
 *
 * <p>
 * Owning side of the relation with the guild (foreign key {@code guild_id}).
 * A role name is unique within a guild, not globally.
 */
@Entity
@Table(name = "roles", uniqueConstraints = @UniqueConstraint(columnNames = { "guild_id", "name" }))
public class RoleEntity {

    /** Identifier generated by the application (no {@code @GeneratedValue}). */
    @Id
    private UUID id;

    @ManyToOne(optional = false)
    @JoinColumn(name = "guild_id", nullable = false)
    private GuildEntity guild;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private int position;

    /** Default constructor required by the JPA specification. */
    public RoleEntity() {
    }

    /**
     * Convenience constructor used by the mapper.
     *
     * @param id       the identifier
     * @param guild    the owning guild
     * @param name     the role name
     * @param position the rank in the guild hierarchy
     */
    public RoleEntity(UUID id, GuildEntity guild, String name, int position) {
        this.id = id;
        this.guild = guild;
        this.name = name;
        this.position = position;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public GuildEntity getGuild() {
        return guild;
    }

    public void setGuild(GuildEntity guild) {
        this.guild = guild;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }
}
